### ISSUE TITLE
I need to carry the parameters on the casServerLoginUrl

### ISSUE THREAD

**Issue by wxh20114746** [cloudogu/sonar-cas-plugin#9]
For Example, In my  sonar.properties sonar.cas.casServerLoginUrl=https://cas.hitchhiker.com:8443/cas/login?type=xxxxx.
I need to pass the parameter type=xxxxx  to CAS server,But the plugin nonsupport.
Can you improve this code?Thanks!

Regards,

**Comment by ppxl** [comment]
Hi, and thank you for your comment on this. 

Would you kindly elaborate on the background of your question? Like:

- What constellation of SonarQube (esp. the version) and CAS are you using`
- Why is the `type` parameter necessary?
- Are you using additional Identity Providers like Github or Facebook?

In general the CAS log-in transfers close to no data back to SonarQube besides the serviceUrl.

I think it is rather an issue of CAS itself because the log-in URL is sufficiently transferred. But during log-in in the CAS there is another request made, that one that redirects back to Sonar. So we are talking here of two different requests. And said second request is manage by the CAS itself.

**Comment by wxh20114746** [comment]
Thank you for your answer.
I have solved it.



Regards,
